name       : minetest
version    : 0.4.17.1
release    : 5
source     :
    - https://github.com/minetest/minetest/archive/0.4.17.1.tar.gz : cd25d40c53f492325edabd2f6397250f40a61cb9fe4a1d4dd6eb030e0d1ceb59
    - https://github.com/minetest/minetest_game/archive/0.4.17.tar.gz : f0ab07cb47c1540b2016bf76a36e2eec28b0ea7827bf66fc5447e0c5e5d4495d
license    :
    - LGPL-2.1-or-later
    - CC-BY-SA-3.0
summary    : Minetest, an open source infinite-world block sandbox game with survival and crafting.
description: |
    Minetest, an open source infinite-world block sandbox game with survival and crafting.
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(gl)
    - pkgconfig(libcurl)
    - pkgconfig(libjpeg)
    - pkgconfig(libpng)
    - pkgconfig(openal)
    - pkgconfig(sqlite3)
    - pkgconfig(vorbis)
    - bzip2-devel
    - irrlicht-devel
component  : games
setup      : |
    tar -xf $sources/0.4.17.tar.gz
    install -D -d -m 00755 $installdir/usr/share/minetest/games/minetest_game
    cp -r minetest_game-0.4.17/* $installdir/usr/share/minetest/games/minetest_game/
    %cmake_ninja ..
build      : |
    %ninja_build
install    : |
    %ninja_install
