name       : minetest
version    : 0.4.13
release    : 1
source     :
    - http://solus-us.tk/sources/minetest-0.4.13.tar.gz : d77ee70c00a923c3ed2355536997f064a95143d0949a7fc92d725d079edef9f7
    - http://solus-us.tk/sources/minetest_game-0.4.13.tar.gz : 8d1671484fcd62936ae15bf6a2f9fd9863a8fb010bdf8902ba63977395f3b613
license    :
    - LGPL-2.1+
    - CC-BY-SA-3.0
summary    : Minetest, an open source infinite-world block sandbox game with survival and crafting.
description: |
    Minetest, an open source infinite-world block sandbox game with survival and crafting.
builddeps  :
    - pkgconfig(openal)
    - pkgconfig(vorbis)
    - pkgconfig(x11)
    - pkgconfig(gl)
    - pkgconfig(sqlite3)
    - pkgconfig(libpng)
    - irrlicht-devel
    - libjpeg-turbo-devel
rundeps    :
    - irrlicht 
setup      : |
    tar -xf $sources/minetest_game-0.4.13.tar.gz
    mkdir -p %installroot%/usr/share/minetest/games/minetest_game
    cp -r minetest_game-0.4.13/* %installroot%/usr/share/minetest/games/minetest_game/
    %cmake .
build      : |
    %make
install    : |
    %make_install
    # Link up irrlicht
    ln -s /usr/lib64/libIrrlicht.so.1.8.1 /usr/lib64/libIrrlicht.so.1.8
