name       : minetest
version    : 5.7.0
release    : 29
source     :
    - https://github.com/minetest/minetest/archive/refs/tags/5.7.0.tar.gz : 0cd0fd48a97f76e337a2e1284599a054f8f92906a84a4ef2122ed321e1b75fa7
    - https://github.com/minetest/minetest_game/archive/refs/tags/5.7.0.zip : d136bd13738dd5af826c12438049e2688fbe2471a0cc1e493c29fe01efdf0b42
license    :
    - Apache-2.0
    - CC-BY-SA-3.0
    - LGPL-2.1-or-later
    - MIT
component  : games
homepage   : https://www.minetest.net
summary    : Multiplayer infinite-world block sandbox game
description: |
    Minetest is an infinite-world block sandbox game and game engine.
    Players can create and destroy various types of blocks in a three-dimensional open world. This allows forming structures in every possible creation, on multiplayer servers or in singleplayer.
    Minetest is designed to be simple, stable, and portable. It is lightweight enough to run on fairly old hardware.
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(gl)
    - pkgconfig(jsoncpp)
    - pkgconfig(libcurl)
    - pkgconfig(libjpeg)
    - pkgconfig(libpq)
    - pkgconfig(libzstd)
    - pkgconfig(luajit)
    - pkgconfig(openal)
    - pkgconfig(sqlite3)
    - pkgconfig(vorbis)
    - pkgconfig(x11)
    - irrlichtmt-devel
    - leveldb-devel
    - libspatialindex-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    unzip -u $sources/${version}.zip
    install -Ddm00644 $installdir/usr/share/minetest/games/minetest_game
    cp -r minetest_game-${version}/* $installdir/usr/share/minetest/games/minetest_game
