name       : minetest
version    : 0.4.14
release    : 2
source     :
    - https://solus-project.com/sources/minetest-0.4.14.tar.gz : 203de4d41a60466126ab92ca85f726d88d0084f2e78393da239e7416cb847054
    - https://solus-project.com/sources/minetest-game-0.4.14.tar.gz : eebc2830d0e2f431f648691a0072fbb773d000c56deaf09ddc5e7416096cdf85
license    :
    - LGPL-2.1+
    - CC-BY-SA-3.0
summary    : Minetest, an open source infinite-world block sandbox game with survival and crafting.
description: |
    Minetest, an open source infinite-world block sandbox game with survival and crafting.
builddeps  :
    - pkgconfig(openal)
    - pkgconfig(vorbis)
    - pkgconfig(x11)
    - pkgconfig(gl)
    - pkgconfig(sqlite3)
    - pkgconfig(libpng)
    - irrlicht-devel
    - libjpeg-turbo-devel
rundeps    :
    - irrlicht
component  : games
setup      : |
    tar -xf $sources/minetest-game-0.4.14.tar.gz
    install -D -d -m 00755 %installroot%/usr/share/minetest/games/minetest_game
    cp -r minetest_game-0.4.14/* $installdir/usr/share/minetest/games/minetest_game/
    %cmake .
build      : |
    %make
install    : |
    %make_install
