name       : minetest
version    : 5.4.0
release    : 20
source     :
    - https://github.com/minetest/minetest/archive/5.4.0.tar.gz : 6e9b299e156651be9bcf973a9232cff32215de31dfae5ea770a71d1757cab014
    - https://github.com/minetest/minetest_game/archive/5.4.0.zip : 9762fbcc6938468a0de55b5cbeb3bf57e6db24355923f2f7bddd7353e91e5b9d
license    :
    - Apache-2.0
    - CC-BY-SA-3.0
    - LGPL-2.1-or-later
    - MIT
component  : games
homepage   : https://www.minetest.net
summary    : Multiplayer infinite-world block sandbox game
description: |
    Minetest is an infinite-world block sandbox game and game engine.
    Players can create and destroy various types of blocks in a three-dimensional open world. This allows forming structures in every possible creation, on multiplayer servers or in singleplayer.
    Minetest is designed to be simple, stable, and portable. It is lightweight enough to run on fairly old hardware.
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(gl)
    - pkgconfig(jsoncpp)
    - pkgconfig(libcurl)
    - pkgconfig(libjpeg)
    - pkgconfig(luajit)
    - pkgconfig(openal)
    - pkgconfig(sqlite3)
    - pkgconfig(vorbis)
    - pkgconfig(xxf86vm)
    - bzip2-devel
    - irrlicht-devel
    - leveldb-devel
    - libspatialindex-devel
setup      : |
    %cmake_ninja -DENABLE_SYSTEM_JSONCPP=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
    unzip -u $sources/${version}.zip
    install -Ddm00644 $installdir/usr/share/minetest/games/minetest_game
    cp -r minetest_game-${version}/* $installdir/usr/share/minetest/games/minetest_game
