name       : minetest
version    : 0.4.15
release    : 3
source     :
    - https://solus-project.com/sources/minetest-0.4.15.tar.gz : 5684e6118e3484f8901323f1ca4179202659010b33c72f02bc03df792493e3a9
    - https://solus-project.com/sources/minetest-game-0.4.15.tar.gz : f583ea55f511bbcc106c60f7d488ec3fe6b961efc3fd648603b6acd0189d7d8a
license    :
    - LGPL-2.1+
    - CC-BY-SA-3.0
summary    : Minetest, an open source infinite-world block sandbox game with survival and crafting.
description: |
    Minetest, an open source infinite-world block sandbox game with survival and crafting.
builddeps  :
    - pkgconfig(openal)
    - pkgconfig(vorbis)
    - pkgconfig(x11)
    - pkgconfig(gl)
    - pkgconfig(sqlite3)
    - pkgconfig(libpng)
    - irrlicht-devel
    - libjpeg-turbo-devel
rundeps    :
    - irrlicht
component  : games
setup      : |
    tar -xf $sources/minetest-game-${version}.tar.gz
    install -D -d -m 00755 $installdir/usr/share/minetest/games/minetest_game
    cp -r minetest_game-${version}/* $installdir/usr/share/minetest/games/minetest_game/
    %cmake .
build      : |
    %make
install    : |
    %make_install
