name       : minetest
version    : 0.4.16
release    : 4
source     :
    - https://solus-project.com/sources/minetest/minetest-0.4.16.tar.gz : 0ef3793de9f569746ea78af7a66fe96ef65400019e5e64a04a5c3fa26a707655
    - https://solus-project.com/sources/minetest/minetest-game-0.4.16.tar.gz : ea914555949b4faccda5e13143cb021d2f9a5fa19abd1f5e4b7b65004cbd2b5a
license    :
    - LGPL-2.1+
    - CC-BY-SA-3.0
summary    : Minetest, an open source infinite-world block sandbox game with survival and crafting.
description: |
    Minetest, an open source infinite-world block sandbox game with survival and crafting.
builddeps  :
    - pkgconfig(openal)
    - pkgconfig(vorbis)
    - pkgconfig(x11)
    - pkgconfig(gl)
    - pkgconfig(sqlite3)
    - pkgconfig(libpng)
    - irrlicht-devel
    - libjpeg-turbo-devel
rundeps    :
    - irrlicht
component  : games
setup      : |
    tar -xf $sources/minetest-game-${version}.tar.gz
    install -D -d -m 00755 $installdir/usr/share/minetest/games/minetest_game
    cp -r minetest_game-${version}/* $installdir/usr/share/minetest/games/minetest_game/
    %cmake .
build      : |
    %make
install    : |
    %make_install
